### ISSUE TITLE
1.19.2 - Radiation World Sources Tripling on World Start

### ISSUE THREAD

**Issue by nelx-en** [aurilisdev/Nuclear-Science#163]
On world start, radioactive sources in world (not inventory) will Triple their radiation output which will then begin to quickly dissipate to its normal level.

Eg. Throw 1 Polonium-210 on ground, it will emit 2.5k rads. Exit and load into world and it will emit 7.5k rads which will immediately begin to decrease to its baseline level.

Tested with:
Voltaic 1.19.2-1.0.0-5
Electrodynamics 1.19.2-0.8.3-1
Nuclear Science 1.19.2-0.5.4-3

**Comment by skiprocks999** [comment]
this should be resolved in the next update set

**Comment by skiprocks999** [comment]
was this resolved?

**Comment by nelx-en** [comment]
I haven't had the opportunity to use the just-released jars, but with 1.19.2-0.5.4-4 the tripling effect still happened.

And a new quirk appeared where dropping a radioactive item will double its Rads. Eg throwing Polonium on the ground will emit 5k Rads instead of 2.5k.

**Comment by skiprocks999** [comment]
Please see if it still occurs in -6

**Comment by nelx-en** [comment]
> Please see if it still occurs in -6

Tested on -6, effect is still present. Attached below is a video demo. Also note a new bug appeared where throwing radioactive items into the world creates double the rads that should be present. 

https://github.com/user-attachments/assets/72741a0d-71c6-4628-8756-a52f16b0c801

Fissile salt is used as example, 200 rads. 
~Becomes 400 when on ground, as if there is now 2 sources.~ The doubling behaviour on drops seems to be present in several versions, I will open a separate issue.
Then triples on world load plus the "ghost source" (600 + 200) and immediately starts decaying to base value.

**Comment by nelx-en** [comment]
> > Please see if it still occurs in -6
> 
> Tested on -6, effect is still present. Attached below is a video demo. Also note a new bug appeared where throwing radioactive items into the world creates double the rads that should be present.
> rad-triple.mp4
> 
> Fissile salt is used as example, 200 rads. Becomes 400 when on ground, as if there is now 2 sources. Then triples on world load plus the "ghost source" (600 + 200) and immediately starts decaying to base value.

The doubling behaviour seems to be present in several versions, I will open a separate issue.

**Comment by aurilisdev** [comment]
Will check if this also happens in 1.21

**Comment by aurilisdev** [comment]
Fixed this now :)
